#!/usr/bin/env python3
"""Turn SCENARIO.md into machine-readable JSON so the prose and the data can't drift.

CI regenerates this and fails if the committed JSON differs, which means the script
humans read and the script the validator enforces are always the same script.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCENARIO_MD = ROOT / "SCENARIO.md"

MSG = re.compile(r"^(\d+)\.\s+`(.+?)`(?:\s+←\s+probe\s+(R\d+))?")
PROBE_ROW = re.compile(r"^\|\s*(R\d+)\s*\|\s*(.+?)\s*\|$")


def parse(md: str) -> dict:
    version = re.search(r"^#\s+Core scenario,\s+v([\d.]+)", md, re.M)
    if not version:
        sys.exit("SCENARIO.md: no version heading found")

    sessions: dict[str, list] = {}
    current = None
    probes: dict[str, str] = {}
    in_probe_table = False

    for line in md.splitlines():
        if line.startswith("## Session 1"):
            current = "1"
            sessions[current] = []
            continue
        if line.startswith("## Session 2"):
            current = "2"
            sessions[current] = []
            continue
        if line.startswith("## Probe scoring"):
            current = None
            in_probe_table = True
            continue
        if line.startswith("## ") and not line.startswith("## Probe scoring"):
            if in_probe_table:
                in_probe_table = False
            current = None
            continue

        if current:
            m = MSG.match(line.strip())
            if m:
                sessions[current].append(
                    {"n": int(m.group(1)), "text": m.group(2), "probe": m.group(3)}
                )
        elif in_probe_table:
            p = PROBE_ROW.match(line.strip())
            if p and p.group(1) != "Probe":
                probes[p.group(1)] = p.group(2)

    for s, msgs in sessions.items():
        expected = list(range(1, len(msgs) + 1))
        if [m["n"] for m in msgs] != expected:
            sys.exit(f"SCENARIO.md session {s}: message numbering is not 1..n")

    return {
        "scenario_version": version.group(1),
        "source": "SCENARIO.md",
        "note": "Generated by tools/extract_scenario.py. Edit SCENARIO.md, not this file.",
        "sessions": {
            s: [{"n": m["n"], "text": m["text"], "probe": m["probe"]} for m in msgs]
            for s, msgs in sessions.items()
        },
        "probes": probes,
    }


def main() -> int:
    data = parse(SCENARIO_MD.read_text())
    out = ROOT / "scenario" / f"v{data['scenario_version']}.json"
    rendered = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    if "--check" in sys.argv:
        if not out.exists():
            print(f"FAIL: {out.relative_to(ROOT)} is missing")
            return 1
        if out.read_text() != rendered:
            print(f"FAIL: {out.relative_to(ROOT)} is out of sync with SCENARIO.md")
            print("Run: python3 tools/extract_scenario.py")
            return 1
        print(f"OK: {out.relative_to(ROOT)} matches SCENARIO.md")
        return 0

    out.parent.mkdir(exist_ok=True)
    out.write_text(rendered)
    total = sum(len(v) for v in data["sessions"].values())
    print(f"wrote {out.relative_to(ROOT)}: {total} messages, {len(data['probes'])} probes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
